### ISSUE TITLE
Manual dran'n'drop group edit

### ISSUE THREAD

**Issue by AlexKatyukov** [jonatanklosko/groupifier#10]
One think that I dream for. I want to have a possibility to change competitor groups manually. It's not high-priority, but sometimes it can be good.

**Comment by jonatanklosko** [comment]
This is already tracked by #4.

**Comment by AlexKatyukov** [comment]
My bad :)

**Comment by jonatanklosko** [comment]
No worries, it's not clear from the issue straightaway, but there is already some discussion so I went with that ^^
