### ISSUE TITLE
Bug in Multi-blind scorecard generation

### ISSUE THREAD

**Issue by EdHollingdale** [jonatanklosko/groupifier#16]
For several competitions with multiblind in Melbourne Groupifier has only generated ~half the multiblind scorecards required. At first I thought it was an issue with multiblind being on multiple stages (see AltonaAlgorithms2019 and MelbourneSummer2020) but I've been told it was an issue for MelbourneCubeDays2019 as well. This isn't a huge issue as it is easy to write out the ~15 extra scorecards by hand, but it is frustrating.

**Comment by EdHollingdale** [comment]
Actually I have been corrected - this issue was not present for MelbourneCubeDays2019. I suspect then multiple stages/rooms are the cause for only half the multiblind scorecards being generated.

**Comment by jonatanklosko** [comment]
Fixed in 1f107e23129a93f90922bcdd09d2f8af45ca306e =)
