### ISSUE TITLE
Fix Scorecard Cutoffs

### ISSUE THREAD

**Issue by sam596** [jonatanklosko/groupifier#17]
As spoken about in the Guildford Open 2020 report, it seems that cutoffs are not defined as say "40.00 seconds" but instead "> 40.00 seconds".

If a less than sign could be added to groupifier scorecards, it would be a lot less ambiguous than the regulations.

**Comment by jonatanklosko** [comment]
> As spoken about in the Guildford Open 2020 report, it seems that cutoffs are not defined as say "40.00 seconds" but instead "> 40.00 seconds".

Not entirely sure what you mean by `defined as "> 40.00 seconds"`, but I get the point.

I think it would be weird to say `cutoff < 10.00`, so perhaps something like that:

![image](https://user-images.githubusercontent.com/17034772/73348367-940c2c80-4289-11ea-9c4a-6ecbff670937.png)

compared to the current

![image](https://user-images.githubusercontent.com/17034772/73348395-9f5f5800-4289-11ea-93e2-6132485467ca.png)

And for MBLD that would be `Cutoff: (>) X points`.

What do you think?

**Comment by sam596** [comment]
Just the way it was worded in the report implied that there is no such thing as a cutoff of 40.00, only <40.00.

Personally I don't think there's anything wrong with having it saying

> Cutoff: <1:10.00

But I just thought it should be clear.

**Comment by jonatanklosko** [comment]
Alright! I went for `< 1:10.00` (621a91273dfa4d1113f79504ed0a4ec869a991e3).
