### ISSUE TITLE
Issue while saving the data 

### ISSUE THREAD

**Issue by saitep** [jonatanklosko/groupifier#18]
Getting the following response while saving the groups:
{
  "status": "Error while saving WCIF",
  "error": "The property '#/persons/104/countryIso2' of type null did not match the following type: string"
}

**Comment by jonatanklosko** [comment]
Hey, this is actually not Groupifier but the WCA website that causes this error. It validates that every competition person has gender, country and name set, but at the same time it allows you to add an organizer that doesn't have that information. In this particular case the account `The Mathematics Society, St. Stephen's College` is missing this information and that causes the trouble. Please fill that information (although it doesn't make much sense) on the WCA website and saving should work properly =)
