### ISSUE TITLE
Pick scramblers before group assignment

### ISSUE THREAD

**Issue by KitClement** [jonatanklosko/groupifier#2]
As brought up by Caleb in CF:

> My only problem is that it puts people into groups, then it allows me to select certain scramblers. This creates a case where all the people I wanted to have scramble were in the same group instead of spread out.

**Comment by jonatanklosko** [comment]
This doesn't fit to the current philosophy of not requiring too much config and trying to provide the best outcome. Also this doesn't really fit to what the app does do now, i.e. if you select scramblers, you do this as the computation goes. What you think of is more like a full control over the assignments, if I decide to implement something like this, then I'd certainly wait until WCA supports importing registrations from CSV, which means that WCIF would always include registered people and the app would be able to persist assignments data whenever you make a change. Not something I plan to do soon.

**Comment by pedrosino** [comment]
+1 for this.

Since the app puts the best people in the same group, the best scramblers are probably together, so you're left with ok-ish people to scramble for the best group.

**Comment by jonatanklosko** [comment]
Closing as this tool is now deprecated in favor of more powerful [groupifier-next](https://github.com/jonatanklosko/groupifier-next).
