### ISSUE TITLE
Lowercasing hyphenated name

### ISSUE THREAD

**Issue by KitClement** [jonatanklosko/groupifier#3]
Just ran a test case for an upcoming competition, and had the following competitor as in their registration

> Asher Kim-Magierek

show up as this name in all of the output PDFs:

> Asher Kim-magierek

I'm guessing that the program has some logic to autocorrect casing of names. I think it would be best to leave it to the name as shown in their profile, and let delegates be sure that new competitors have proper formatting of names.

**Comment by jonatanklosko** [comment]
Thanks for noticing this! Yeah, I did this when I noticed some competitors registering with upper case names and I found those names looking really unaesthetic on scorecards and summary lists. Why shouldn't the app take care of correcting the case to look neater and more consistent?

**Comment by KitClement** [comment]
I guess my thought is that at least for competitors who have competed before, this validation is already done by their results being submitted from the first competition. Delegates should be making sure that new competitors have properly formatted names before results submission as well. 

I also feel like there's potentially contradicting rules for how names should be formatted. Some hyphenated names may not need capitalization if the hyphen is part of the name, but if the hyphen is due to merging two names by marriage, they should both be capitalized. I'm not sure if you are auto-capitalizing all parts of the names as well, but if so, this would fail for a name like "Arnaud van Galen", where a part of the name shouldn't be capitalized.

**Comment by jonatanklosko** [comment]
The CSV file can come from any registration system, so relying on validations won't always work. Anyway, you convinced me with the "Arnaud van Galen" example, I will leave the names unchanged.

**Comment by jonatanklosko** [comment]
Fixed in 8139bb32cbca1ba296c257bf3b47c0e3d4247563.
