### ISSUE TITLE
Hint text to explain why options can't be edited

### ISSUE THREAD

**Issue by kr-matthews** [jonatanklosko/groupifier#37]
I had a competition this past weekend and the organizers couldn't edit the group sizes, nor the number of scramblers/runners. The options were greyed out:
![image](https://user-images.githubusercontent.com/49137025/146116017-525ffe49-1c79-43c4-b233-b6fb21346baf.png)

They asked me to take a look and I also couldn't figure it out for a long time, until I realized that they had already generated groups/assignments and that that prevents you from editing parameters (as far as I can tell). If you don't know that someone else already generated groups (the situation I was in) then it's not obvious what's going on. And even if you do know (the situation the organizers were in) then it's still potentially very confusing.

This also prompted a vague memory I had of something like this happening a couple of years ago, so it doesn't seem to just be a one-time thing.

My suggestion is that when an option is greyed out, if there could a hint somewhere (maybe on hover) which explains why it can't be edited.

**Comment by jonatanklosko** [comment]
Hey @kr-matthews, thanks for the report! I've just added tooltips that should make this scenario more clear :)

**Comment by kr-matthews** [comment]
Thanks!
