### ISSUE TITLE
Stages/Simultaneous Groups

### ISSUE THREAD

**Issue by TheMagicCuber** [jonatanklosko/groupifier#45]
Is it possible to assign "stages" or rather multiple groups going at once without conflict? i.e. having groups 1 and 2 go at the same time, but no one in group 1 is doing anything in group 2.
Thanks!

**Comment by jonatanklosko** [comment]
Hey @TheMagicCuber! It is supported, you just need to create two (or more) rooms in the schedule on the WCA website, one for each stage. Then you can mirror the event activities in the other room. See [this schedule](https://www.worldcubeassociation.org/competitions/SlowNSteadyWinter2020#competition-schedule) as an example, if you look at the "Calendar" view, it should clarify the idea :)

**Comment by TheMagicCuber** [comment]
Ah ok that makes sense, thank you!
