### ISSUE TITLE
Allow printing of blank scorecards for subsequent rounds

### ISSUE THREAD

**Issue by Mollerz** [jonatanklosko/groupifier#5]
It is quite common that we cannot bring printers to competition, and so for 2nd/3rd/4th rounds we often have to write them all out manually. If we could have the option to print out for example 3x3 Round 2 scorecards, but with the name field being empty, that would save us a lot of time at the competition!

**Comment by jonatanklosko** [comment]
Closing as this tool is now deprecated in favor of more powerful [groupifier-next](https://github.com/jonatanklosko/groupifier-next).
