### ISSUE TITLE
Group Assignments not ordered correctly

### ISSUE THREAD

**Issue by sam596** [jonatanklosko/groupifier#51]
Ordered as text rather than ints?

![image](https://user-images.githubusercontent.com/31994452/186207110-fbf48e4e-248d-4e40-9bfa-1b943a7bf8bc.png)

**Comment by jonatanklosko** [comment]
Actually, currently there was no explicit order, the groups would appear in the order they were assigned. Generally it would show up as expected, but the order gets shuffled when editing assignments manually.

Fixed in eae9d2e1c18d13a4f481a9f52bf5a132abcf6060!
