### ISSUE TITLE
Scorecards not generated for competitors with 4 digit ID

### ISSUE THREAD

**Issue by EdHollingdale** [jonatanklosko/groupifier#56]
If a competitor has a 4 digit registrantID groupifier does not generate a scorecard for them. They appear in the group overview and on competitor cards, but they do not have a scorecard. OC2022 has 4 competitors with a registrantID of 1000 or higher.

**Comment by jonatanklosko** [comment]
Fixed in 6b0eacfe9be8e983ad1c35fda298c0bf14b4dd52.

The scorecards were actually there when using 4 scorecards per page, but 4-digit id shifted the scorecard and made it overlap with the one below. When using 1 scorecard per page, the overlapping would cause the scorecard to disappear.
