### ISSUE TITLE
Competitor card download nor working

### ISSUE THREAD

**Issue by druidalek** [jonatanklosko/groupifier#6]
![image](https://user-images.githubusercontent.com/4152162/66872707-eb221600-efa6-11e9-9de7-0c1fce684886.png)
I'm getting an error while trying to download the competitor cards. If you can hijack any competition the one I'm trying to use is "Macedonian Nationals 2019". Is there something I'm doing wrong?

**Comment by jonatanklosko** [comment]
I figured out it's because some new competitors registered after you created groups, so they had no groups assigned at all. To fix it I went to Group manager, cleared tasks and assigned them again. You should be able to print the cards now. This bug is already tracked by #2 so I'm gonna close it.

**Comment by druidalek** [comment]
Registration is still open, so I only needed the file to plan for printing etc, but it's good to know what the issue was and how to fix it. Maybe a friendly message of the issue should be included in the app itself - although apart from me testing right now, I would assume almost everyone uses groupifier after registration is closed, so it's a rare issue. 

Thanks for the quick answers.
