### ISSUE TITLE
Scorecard cutoff and time limits 23 hours

### ISSUE THREAD

**Issue by jbrungar** [jonatanklosko/groupifier#6]
I just did a test run using this tool and all of the scorecards have 23 hours in front as in the screenshot.
![cutoff and time limit 23 hours](https://user-images.githubusercontent.com/6947050/40354387-d93eb790-5e07-11e8-93b2-295fa4bb9b21.png)

**Comment by jonatanklosko** [comment]
Hey @jbrungar, that's indeed really weird behaviour! What browser are you using? Would it be possible for you to check it in another browser as well?

**Comment by jbrungar** [comment]
Chrome on macOS. Just tried Firefox and it does the same there too.

**Comment by jbrungar** [comment]
1969-12-31T23:00:45.000Z

**Comment by jonatanklosko** [comment]
What about the second line? (I've just edited the comment)

**Comment by jbrungar** [comment]
1970-01-01T00:00:45.000Z

**Comment by jonatanklosko** [comment]
Cool, thanks! Now I know where the problem lies and how to fix it =) Just for the reference, it's related to the problem described [here](https://stackoverflow.com/q/41280708). I will deploy the fix shortly!

**Comment by jonatanklosko** [comment]
Fixed in aae6a3f65ac944695a6b197f43245a850d254928.
@jbrungar please let me know if scorecards are generated correctly now =)

**Comment by jbrungar** [comment]
Yes, they are correct now, thanks.
