### ISSUE TITLE
Number of groups/scrambling sets altered on WCA-page?

### ISSUE THREAD

**Issue by WilhelmKilders** [jonatanklosko/groupifier#64]
Hi, 
I'm not sure if this is a bug or a feature. 
We have noticed that when creating the grouping in groupifier it won't use the given number of scrambling sets from the WCA-page. Instead the number of groups get calculated in groupifier and I see how this could be useful. But then once you save the grouping in groupifier it seems to override the given number of scrambling sets on the WCA-page. At least I think thats whats happening. 
We've had multiple instances where the number of scrambling sets was altered after we've created the groups. This went unnoticed a few times resulting in the wrong amount of scrambles being generated.
Is this a feature of groupifier or is it a bug? If its a feature I think a warning message in groupifier would be helpful. I wouldn't expect a third party tool changing the settings for a comp on the WCA-page.

If there is nothing in the code that could cause this, we will investigate closer the next time to see what's causing the problem mentioned :).

Best, Wilhelm

**Comment by jonatanklosko** [comment]
Hey, you are correct, Groupifier assumes it is the one controlling groups and it does set the number of scramble sets on the WCA website to match the number of groups. Without that people would need to manually replicate the number of scramble sets, which would be error-prone and easy to forget. In what scenario do you use different number of scramble sets than groups?

In "Manage groups" the group creation prompt actually mentiones that scramble sets are adjusted: "To assign tasks you need to create groups first. This will also determine scramble set count for each round."

> I wouldn't expect a third party tool changing the settings for a comp on the WCA-page.

Actually that's oftentimes exactly what the tools are supposed to do, but it's not always visible. For example Groupfier (and other scheduling tools) create group entries in the schedule, but the schedule is not displayed with that granularity on the website. WCA Live (which is essentially a third-party tool, just under the official umbrella) saves live results into the WCA website. We have a whole specification that allows tools to exchange and modify data, each serving its specific purpose :)

**Comment by WilhelmKilders** [comment]
Again, thanks for the quick response and thanks for clarifying :).

Ok, doing it this way around does also make sense and I thought about it yesterday after writing the issue. 
It not that we need different amount of scramble sets compared to groups.
We usually just have a different workflow when planning a comp. When creating the schedule we already plan the number of stations per stage. Based on experience and assumptions we plan how many groups we will need per event and already set the number of scrambling sets on the WCA-page. Once the competitor limit has been reached or we are about 2 weeks out of comp we adjust the number of scrambling sets manually based on the actual number of registrations. From there we assumed that groupifier would use this data as an input for the assignments when in reality its supposed to work the other way around.
I guess it makes sense, that "groupifier" takes care of the groups and thus also the scrambling sets. 
The issue arose when our number planned number of groups differed from those that groupifier calculated and saved the progress in groupifier right after creating the groups before we checked each event.

Regarding the info message in the manage groups section we must've missed it in the past.
I have also never thought about it this way but yes, obiously third party tools do modify data on the WCA-page :).

Good to know for us that this is a feature and we will try to adjust our workflow to fit groupifier better. 
Thanks for all the work you've put in to this! Having organised comps since 2015 these tools are a massive benefit and make live much easier.

**Comment by jonatanklosko** [comment]
Yeah, approaching it from the other side is what Groupifier assumes, that is configuring groups within Groupifier itself. You can also do that in advance and then adjust all counts before actually creating the groups, but it's usually more convenient to do it once everybody registers, so that the suggested group sizes are more accurate. Sourcing the scramble set info from WCA would be less intuitive (people would need to know to do it first) and it's a bit limiting once there are parallel groups/stages. On the other hand figuring out the number of necessary scramble sets once all groups are created is straightforward and hence can be automatic :)
