### ISSUE TITLE
Unable to adjust timing stations

### ISSUE THREAD

**Issue by SpeedSkewber** [jonatanklosko/groupifier#66]
For some reason, I cannot adjust the timing stations section in the Groupifier. It currently is 16 and should be 20.

**Comment by jonatanklosko** [comment]
Hey, which competition does that happen for? One case where this happens is if you already assigned groups, you can clear groups and then it should be editable again.

**Comment by SpeedSkewber** [comment]
Hello there! Thanks for responding quickly! It is for Get to Work Chicagoland 2023.Thanks!Jacob WilsonOn Aug 4, 2023, at 3:57 AM, Jonatan Kłosko ***@***.***> wrote:﻿
Hey, which competition does that happen for? One case where this happens is if you already assigned groups, you can clear groups and then it should be editable again.

**Comment by jonatanklosko** [comment]
I see, if you go to "Configure", you need to "Clear" there as well, because all of the rounds configuration (number of groups, scramblers, etc) is suggested based on the number of stations.

**Comment by SpeedSkewber** [comment]
Ok. Thanks so much!Jacob WilsonOn Aug 4, 2023, at 9:48 AM, Jonatan Kłosko ***@***.***> wrote:﻿
Closed #66 as completed.
