### ISSUE TITLE
Option to print one scorecard per registered competitor for non-first round

### ISSUE THREAD

**Issue by JonEsparaz** [jonatanklosko/groupifier#70]
For a top-75% second round (or some other relaxed advancement condition), it is often convenient to print one scorecard per competitor with a blank group number (and blank station number, if applicable), then handwrite the group number for competitors who advance and discard the remaining scorecards.

Ideally, these would print in alphabetical order by competitor name.

**Comment by jonatanklosko** [comment]
I would be fine with adding an option to the scorecards printing that hides round/group, then you could print first rounds with that option. Sidenote: I'm not a fan of the idea of always throwing away 25% scorecards :)

**Comment by JonEsparaz** [comment]
> Sidenote: I'm not a fan of the idea of always throwing away 25% scorecards :)

I also debate whether or not this is the best (or most eco-friendly) option.

> I would be fine with adding an option to the scorecards printing that hides round/group, then you could print first rounds with that option.

Our use case for this is pretty rare (only when we have two rounds of the same event with top-75% advancement back-to-back), but I'm starting to just schedule time for printing. Can you think of other use cases for hiding round/group? I'd rather not implement features that don't have wide utility.

**Comment by jonatanklosko** [comment]
> Can you think of other use cases for hiding round/group?

Not really, note that currently it's possible to print scorecards for second round with round filled in, but without groups and without names, so then the names need to be filled in. So if all scorecards are needed in advance, that's probably a fair option.

I'm fine accepting a PR if you have a use case, otherwise I wouldn't add it :)

**Comment by JonEsparaz** [comment]
I think our use case is an edge case. If we _really_ want the format I've described, it's easy enough to make on localhost. I'd rather not create confusion for non-power users :)

**Comment by jonatanklosko** [comment]
Sounds good!
