### ISSUE TITLE
Printing Errors 

### ISSUE THREAD

**Issue by 2021WHIT02** [jonatanklosko/groupifier#72]
The website is not letting me print scorecards.

**Comment by jonatanklosko** [comment]
The background URL must point to an image available online, for example [this](https://www.worldcubeassociation.org/rails/active_storage/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVkvIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--215ef18c002f1c8801c57e8b6279f473fd43704b/image.png). If it's not available anywhere yet, you can upload to Imgur or similar.
