### ISSUE TITLE
Groupifier won't print scorecards after generating groups with Delegate Dashboard

### ISSUE THREAD

**Issue by LeviGibson** [jonatanklosko/groupifier#75]
The button for Print Scorecards is grayed out. If I remember correctly, I should be seeing a menu with a bunch of checkboxes asking which groups I want to print, but it's not there. I tried a different browser as well :)
Competitor cards and Blank Scorecards print fine for some reason. 
![image](https://github.com/jonatanklosko/groupifier/assets/72767501/951384ac-0230-4561-a1be-f16923fdf1f8)
The competition is on Saturday, so this is a little bit timely. If a developer could send me the PDF directly that would also be fine, if the bug takes time to fix. My settings are screenshotted below. Thanks dev team!
![image](https://github.com/jonatanklosko/groupifier/assets/72767501/f934787d-d324-4b0f-8628-616a477f7174)

**Comment by LeviGibson** [comment]
Nevermind! Found a solution

**Comment by jonatanklosko** [comment]
The competition you showed is finished, and finished rounds are not listed. I assume you meant to navigate to a different competition :)
