### ISSUE TITLE
Person filter doesn't reset page count.

### ISSUE THREAD

**Issue by druidalek** [jonatanklosko/groupifier#8]
I think it's more intuitive if search brings you back to page 1 instead of showing an empty page.

![image](https://user-images.githubusercontent.com/4152162/67330962-735f6880-f51d-11e9-93e2-ee398c1283ca.png)

I have no permissions to submit a pull request but using the following code in RolesManager.js works just fine:

```jsx
const handleSearchStringChange = value => {
  setSearchString(value);
  setPage(0);
};

<TextField
  label="Search"
  value={searchString}
  onChange={event => handleSearchStringChange(event.target.value)}
/>
```

**Comment by jonatanklosko** [comment]
This definitely makes sense, what do you mean don't have permissions to open a PR?

**Comment by druidalek** [comment]
I branched off from master and made the changes, but I couldnt push the branch.

**Comment by jonatanklosko** [comment]
You have to fork the repository first, which creates your own copy of it. Then you can push branches to that fork and create pull requests. If you'd rather me make the change, let me know!

**Comment by druidalek** [comment]
You are totally right. Initiated a pull request by myself.
